/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tradutorlinguagens;

import java.awt.Image;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;

/**
 *
 * @author TheOwnzs
 */
public class Main extends javax.swing.JFrame {

    private LinguagemNatural natural;
    private LinguagemJava javaa;
    private LinguagemFortran fortran;
    private LinguagemMaquina maquina;
    private String texto;
    
    /**
     * Creates new form Main
     */
    public Main() {
        javaa = new LinguagemJava();
        fortran = new LinguagemFortran(this);
        maquina = new LinguagemMaquina();
        this.natural = new LinguagemNatural();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/tradutorlinguagens/imagens/icone.png")));
       

        //adicionar observadores
        this.natural.adicionarObserver(javaa);
        this.natural.adicionarObserver(fortran);
        this.natural.adicionarObserver(maquina);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areaFortran = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaNatural = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaJava = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        areaMaquina = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LangProgTranslator - Tradutor de Linguagens de Programação");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setResizable(false);

        areaFortran.setEditable(false);
        areaFortran.setColumns(20);
        areaFortran.setRows(5);
        jScrollPane1.setViewportView(areaFortran);

        areaNatural.setColumns(20);
        areaNatural.setRows(5);
        areaNatural.setName(""); // NOI18N
        areaNatural.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                areaNaturalKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(areaNatural);

        areaJava.setEditable(false);
        areaJava.setColumns(20);
        areaJava.setRows(5);
        jScrollPane3.setViewportView(areaJava);

        areaMaquina.setEditable(false);
        areaMaquina.setColumns(20);
        areaMaquina.setRows(5);
        jScrollPane4.setViewportView(areaMaquina);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tradutorlinguagens/imagens/Imagem.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Linguagem de Máquina:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Linguagem natural:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Código em JAVA:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Código em Fortran:");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tradutorlinguagens/imagens/computaao.png"))); // NOI18N

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(102, 102, 102)));

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tradutorlinguagens/imagens/settings.png"))); // NOI18N
        jMenu3.setText("Funcionamento");
        jMenu3.setAutoscrolls(true);
        jMenu3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenu3.setMargin(new java.awt.Insets(0, 10, 0, 10));

        jMenuItem3.setText("Como utilizar");
        jMenuItem3.setToolTipText("");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tradutorlinguagens/imagens/list.png"))); // NOI18N
        jMenu1.setText("Lista de comandos");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(0, 10, 10, 0));
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dsadada(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(255, 51, 51));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tradutorlinguagens/imagens/close.png"))); // NOI18N
        jMenu2.setText("Sair");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sair(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(jLabel3)
                            .addGap(114, 114, 114)
                            .addComponent(jLabel4)
                            .addGap(114, 114, 114)
                            .addComponent(jLabel5)
                            .addGap(136, 136, 136)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel7))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Tradutor de Linguagens");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void areaNaturalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_areaNaturalKeyPressed

        //Verifica se a TECLA ENTER foi pressionada
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //PEGA TODO TEXTO
            String lines = areaNatural.getText();
            //SETA LINGUAGEM
            natural.setLinguagem(lines);
            //LIMPA TODOS JTEXTAREA
            areaJava.setText("");
            areaFortran.setText("");
            areaMaquina.setText("");
           //Preenche os outros JTexAreas com as linguagens geradas com o metodo atualizar(observer)
            areaJava.append(javaa.getLinguagem());
            areaFortran.append(fortran.getLinguagem());
            areaMaquina.append(maquina.getLinguagem());

        }
    
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE ||evt.getKeyCode() == KeyEvent.VK_DELETE ) {
              
            //LIMPA TODOS JTEXTAREA
            areaJava.setText("");
            areaFortran.setText("");
            areaMaquina.setText("");
            //PEGA TODO TEXTO
            String lines = areaNatural.getText();
            
            //SETA LINGUAGEM            
            natural.setLinguagem(lines);

            //Preenche os outros JTexAreas com as linguagens geradas com o metodo atualizar(observer)
            areaJava.append(javaa.getLinguagem());
            areaFortran.append(fortran.getLinguagem());
            areaMaquina.append(maquina.getLinguagem());
        }

    }//GEN-LAST:event_areaNaturalKeyPressed
    //Atualiza os JTextAreas usando o exemplo dado
    public void setExemplo(String texto) {
        if(texto ==null){
            areaNatural.setText("");
            areaJava.setText("");
            areaFortran.setText("");
            areaMaquina.setText("");
        }
            natural.setLinguagem(texto);
            //Preenche os outros JTexAreas com as linguagens geradas com o metodo atualizar(observer)
            areaNatural.append(natural.getLinguagem());
            areaJava.append(javaa.getLinguagem());
            areaFortran.append(fortran.getLinguagem());
            areaMaquina.append(maquina.getLinguagem());
    }
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Funcionamento lista = new Funcionamento(this);
        lista.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void dsadada(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsadada
        ListaComandos lista = new ListaComandos(this);
        lista.setVisible(true);
    }//GEN-LAST:event_dsadada

    private void sair(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sair
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_sair

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);

            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaFortran;
    private javax.swing.JTextArea areaJava;
    private javax.swing.JTextArea areaMaquina;
    private javax.swing.JTextArea areaNatural;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
